"""
Edge orbit computation under a group action.

get_edge_orbits(G_sage, generators) partitions the edges of G into orbits
under the group generated by the given permutations.  Pass the result
directly to find_orbit_isometric_embedding in solvers.py.

Typical usage:

    aut_gens = G.automorphism_group().gens()
    edge_orbits = get_edge_orbits(G, aut_gens)

generators are Sage PermutationGroupElement objects (callable as g(v)).
The BFS touches no Sage objects after the initial edge extraction, so the
inner loop is pure Python.
"""

from collections import deque


def get_edge_orbits(
    G_sage,
    generators: list,
) -> list[list[tuple[int, int]]]:
    """
    Partition the edges of G_sage into orbits under the group generated
    by generators.

    Parameters
    ----------
    G_sage : sage.graphs.graph.Graph
        Graph with integer vertices 0..n-1.
    generators : list of PermutationGroupElement
        Generators of the symmetry group to use.  Callable as g(v).

    Returns
    -------
    list of list of (int, int)
        Partition of edges into orbits.  Each edge is canonicalized as
        (min(u, v), max(u, v)).
    """
    edges = [_canon(u, v) for u, v in G_sage.edges(labels=False)]
    unvisited = set(edges)
    orbits = []

    while unvisited:
        seed = next(iter(unvisited))
        unvisited.remove(seed)
        orbit = [seed]
        queue = deque([seed])

        while queue:
            u, v = queue.popleft()
            for g in generators:
                img = _canon(g(u), g(v))
                if img in unvisited:
                    unvisited.remove(img)
                    orbit.append(img)
                    queue.append(img)

        orbits.append(orbit)

    return orbits


def _canon(u, v) -> tuple[int, int]:
    u, v = int(u), int(v)
    return (u, v) if u <= v else (v, u)
